version: '3.4'
services:
  mysql:
    container_name: ts_mysql_container
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=ts_development
      - MYSQL_HOST=127.0.0.1
      - MYSQL_ROOT_HOST=%
    volumes:
      - ts_db_data:/var/lib/mysql
  redis:
    container_name: ts_redis_container
    image: redis:6.0
    ports:
      - "6379:6379"
volumes:
  ts_db_data:
